name: riscv-mini Tests

on: [push, pull_request]

jobs:
  test:
    name: Scala Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: ./.github/workflows/setup-oss-cad-suite
      with:
        osscadsuite-version: '2022-02-02'
    - name: Scala Unit Tests
      run: sbt "testOnly -- -l IntegrationTest"

  integration-tests:
    name: Scala Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: ./.github/workflows/setup-oss-cad-suite
      with:
        osscadsuite-version: '2022-02-02'
    - name: Scala Integration Tests
      run: sbt "testOnly -- -n IntegrationTest"

  make-integration-tests:
    name: Makefile based Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: ./.github/workflows/setup-oss-cad-suite
      with:
        osscadsuite-version: '2022-02-02'
    - name: Install CIRCT
      uses: ./.github/workflows/install-circt
      with:
        version: 'firtool-1.37.0'
    - name: Makefile Integration Tests
      run: make run-tests

  doc:
    name: Documentation and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Documentation
        id: doc
        run: sbt doc
      - name: Check Formatting
        run: sbt scalafmtCheckAll

  all_tests_passed:
    name: "all tests passed"
    needs: [test, doc, integration-tests, make-integration-tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success!